services:
  db:
    image: mysql
    ports:
      - '13000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123mudar
      MYSQL_USER: 123mudar
      MYSQL_PASSWORD: 123mudar
      MYSQL_DATABASE: dbmscostumer
